[mypy]
python_version = 3.12
mypy_path = $MYPY_CONFIG_FILE_DIR/src
files = $MYPY_CONFIG_FILE_DIR/src
# Because many third-part libraries, like ones from Hugging Face, do provide
# library stubs or a `py.typed` marker. Use the following setting to force mypy
# to analyze these packages.
follow_untyped_imports = True
# Force typed function definition
disallow_untyped_defs = True
disallow_incomplete_defs = True
disallow_untyped_decorators = True
