FROM riscv64/ubuntu:22.04

RUN mkdir -p /opt/install-test-deps/
COPY ../script/ubuntu/apt_install.sh /opt/install-test-deps/
COPY ../script/ubuntu/install_test.sh /opt/install-test-deps/
RUN /opt/install-test-deps/install_test.sh
