name: LLVM Release Build for Instruction Scheduling
description: Configuration to create release builds LLVM Toolchain for instruction scheduling
srcDir: /opt/code/compilers/llvm-project/llvm
buildDir: /opt/build/llvm/inst-sched/release-build
installDir: /opt/build/llvm/inst-sched/release-install
packagePathPrefix: /opt/build/llvm/inst-sched/clang-release
buildTool:
  name: cmake
  customConfigureOptions:
    CMAKE_BUILD_TYPE: "Release"
    CMAKE_EXPORT_COMPILE_COMMANDS: "ON"
    LLVM_ENABLE_PROJECTS: "clang"
    LLVM_TARGETS_TO_BUILD: "AArch64;AMDGPU;NVPTX;RISCV;X86"
    LLVM_CCACHE_BUILD: "ON"
    # BUILD_SHARED_LIBS: "ON"
    LLVM_BUILD_EXAMPLES: "OFF"
    LLVM_BUILD_BENCHMARKS: "OFF"
    LLVM_BUILD_TESTS: "ON"
    # LLVM_ENABLE_RTTI: "ON"
    # LLVM_ENABLE_EH: "ON"
    # LLVM_ENABLE_ASSERTIONS: "ON" # Enable debug level logging
    # LLVM_ENABLE_DUMP: "ON" # Enable dumping
    # To enable benchmarking functionalities of `llvm-exegesis`.
    LLVM_ENABLE_LIBPFM: "ON"
toolchain:
  name: llvm
compilerOption:
  # cflags:
    # - "-g1" # Emit debug line number tables only
  cxxflags:
    # - "-g1" # Emit debug line number tables only
    - "-stdlib=libc++" # Use LLVM"s libc++
  ldflags:
    - "--rtlib=compiler-rt" # Use LLVM"s compiler-rt
    - "-fuse-ld=wild"
