name: LLVM Toolchain RISCV64
run-name: CI/CD for LLVM Toolchain RISCV64
on:
  schedule:
    # Run at 8:00 UTC every single day
    - cron: '0 8 * * *'
  workflow_dispatch:

env:
  llvm_build_dir: llvm-build
  llvm_source_dir: llvm-project

jobs:
  build:
    name: Build LLVM Toolchain RISCV64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout LLVM build scripts
        uses: actions/checkout@v4
        with:
          path: ${{ env.llvm_build_dir }}
      - name: Checkout LLVM source code
        run: |
          git clone --depth 1 https://github.com/llvm/llvm-project.git ${{ env.llvm_source_dir }}
      - name: Install build dependencies
        run: |
          cd ${{ env.llvm_build_dir }}
          ./script/install_deps_ubuntu.sh
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      - name: Build LLVM RISCV64
        run: |
          cd ${{ env.llvm_build_dir }}
          . venv/bin/activate
          ./script/build_driver.sh --config ./projects/llvm.yaml --package
      - name: Upload LLVM RISCV64 binaries
        uses: actions/upload-artifact@v4
        with:
          name: LLVM RISCV64 binaries
          path: ${{ env.llvm_build_dir }}/out/llvm/clang-riscv64.tar.xz
